# Generated by Django 4.1.3 on 2022-12-18 16:01

import core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=25, validators=[core.validators.check_age])),
                ('company', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Female', max_length=6)),
            ],
            options={
                'verbose_name': 'Основатель',
                'verbose_name_plural': 'Основатели',
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('auto', models.CharField(max_length=255)),
                ('reviews', models.TextField(max_length=500)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.founder')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['name'],
            },
        ),
    ]
